### ISSUE TITLE
network channel problem when use the ACDC dataset

### ISSUE THREAD

**Issue by hanlhan** [arnab39/Semi-supervised-segmentation-cycleGAN#12]
Hi,
    when I use the code and ACDC dataset your provide,  I directly run the commands ` python3 main.py --model 'semisupervised_cycleGAN' --dataset 'acdc' --gpu_ids '6,7' --training True --batch_size 2`, but I got this problem:

```
Training semi-supervised cycleGAN
------------Number of Parameters---------------
[Network Gsi] Total number of parameters : 42.795 M
-----------------------------------------------
------------Number of Parameters---------------
[Network Gis] Total number of parameters : 42.724 M
[Network Gsi] Total number of parameters : 42.795 M
[Network Di] Total number of parameters : 2.765 M
[Network Ds] Total number of parameters : 2.766 M
-----------------------------------------------
 [*] No checkpoint!
Found 808 label images
Found 808 unlabel images
Found 286 val images
learning rate = 0.0002000
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    main()
  File "main.py", line 73, in main
    model.train(args)
  File "/home/h/paper_code/code_test/Semi-supervised-segmentation-cycleGAN1/model.py", line 361, in train
    fake_gt = self.Gsi(unl_img.float())  ### having 21 channels
  File "/home/h/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/h/paper_code/code_test/Semi-supervised-segmentation-cycleGAN1/arch/generators.py", line 431, in forward
    x = self.conv1(x)
  File "/home/h/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/h/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/h/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 64 3 7 7, expected input[2, 1, 256, 256] to have 3 channels, but got 1 channels instead
```

It seems like the input channel of the network is 3, but the ACDC img's channel is 1. How should I modify the code? Thank you very much.

**Comment by mojoee** [comment]
Why is this topic closed? I cant find the solution
