### ISSUE TITLE
Results after training for 300 epochs not satisfying

### ISSUE THREAD

**Issue by mojoee** [arnab39/Semi-supervised-segmentation-cycleGAN#21]
After training for 300 epochs with the standard configuration on the cityscapes dataset, except for the crop size, which I had to downsize to 256x256, the result is just a noise of some random pixel values. Does anyone encounter the same issues?

![image](https://user-images.githubusercontent.com/47809126/79716264-c7021180-8308-11ea-989a-b2266897488f.png)

**Comment by XuanangYou** [comment]
Do you know how to solve this problem?


During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "F:/SemicycleGAN0/Semi-supervised-segmentation-cycleGAN-master/main.py", line 87, in
main()
File "F:/SemicycleGAN0/Semi-supervised-segmentation-cycleGAN-master/main.py", line 73, in main
model.train(args)
File "F:\SemicycleGAN0\Semi-supervised-segmentation-cycleGAN-master\model.py", line 439, in train
fake_gt_discriminator = make_one_hot(fake_gt_discriminator, args.dataset, args.gpu_ids)
File "F:\SemicycleGAN0\Semi-supervised-segmentation-cycleGAN-master\utils.py", line 347, in make_one_hot
one_hot = torch.FloatTensor(labels.size(0), C, labels.size(2), labels.size(3)).zero_()
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

**Comment by ruinianxu** [comment]
@mojoee Hi, I am training it on Cityscapes. After around 200 epoches, mIoU is only around 20%. Did you figure out how to address this issue? Many thanks.
