### ISSUE TITLE
Hello!Code cannot be trained

### ISSUE THREAD

**Issue by XuanangYou** [arnab39/Semi-supervised-segmentation-cycleGAN#23]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "F:/SemicycleGAN0/Semi-supervised-segmentation-cycleGAN-master/main.py", line 87, in <module>
    main()
  File "F:/SemicycleGAN0/Semi-supervised-segmentation-cycleGAN-master/main.py", line 73, in main
    model.train(args)
  File "F:\SemicycleGAN0\Semi-supervised-segmentation-cycleGAN-master\model.py", line 439, in train
    fake_gt_discriminator = make_one_hot(fake_gt_discriminator, args.dataset, args.gpu_ids)
  File "F:\SemicycleGAN0\Semi-supervised-segmentation-cycleGAN-master\utils.py", line 347, in make_one_hot
    one_hot = torch.FloatTensor(labels.size(0), C, labels.size(2), labels.size(3)).zero_()
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

**Comment by Jimmy-FC** [comment]
同样的问题
